"""initial schema

Revision ID: 71d537f70d56
Revises: 
Create Date: 2026-09-13 21:39:53.186301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d537f70d56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('driver_id', sa.String(length=80), nullable=True),
    sa.Column('date_time', sa.String(length=64), nullable=True),
    sa.Column('pickup', sa.String(length=120), nullable=True),
    sa.Column('dropoff', sa.String(length=120), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('dropoff_lat', sa.Float(), nullable=True),
    sa.Column('dropoff_lng', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('trip_start_time', sa.String(length=64), nullable=True),
    sa.Column('trip_end_time', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign', sa.String(length=80), nullable=False),
    sa.Column('slot', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign', 'slot', name='uq_campaign_slot')
    )
    op.create_table('driver_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_positions_driver_id'), ['driver_id'], unique=False)

    op.create_table('drivers',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('license_plate', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('global_time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.String(length=80), nullable=False),
    sa.Column('trip_date', sa.String(length=40), nullable=True),
    sa.Column('trip_time', sa.String(length=40), nullable=True),
    sa.Column('pickup', sa.String(length=120), nullable=True),
    sa.Column('dropoff', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=True),
    sa.Column('paid_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_booking_id'), ['booking_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('route_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.String(length=20), nullable=False),
    sa.Column('driver_id', sa.String(length=80), nullable=True),
    sa.Column('stops_json', sa.Text(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_time_min', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_plans_plan_date'), ['plan_date'], unique=False)

    op.create_table('trip_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=80), nullable=False),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.Column('time', sa.String(length=40), nullable=True),
    sa.Column('pickup', sa.String(length=120), nullable=True),
    sa.Column('dropoff', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_driver', sa.Boolean(), nullable=False),
    sa.Column('registered_address', sa.String(length=255), nullable=True),
    sa.Column('registered_lat', sa.Float(), nullable=True),
    sa.Column('registered_lng', sa.Float(), nullable=True),
    sa.Column('travel_allowance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('waybills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(length=80), nullable=False),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.Column('time', sa.String(length=40), nullable=True),
    sa.Column('pickup', sa.String(length=120), nullable=True),
    sa.Column('dropoff', sa.String(length=120), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penalties')
    op.drop_table('waybills')
    op.drop_table('users')
    op.drop_table('trip_history')
    with op.batch_alter_table('route_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_plans_plan_date'))

    op.drop_table('route_plans')
    op.drop_table('locations')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_booking_id'))

    op.drop_table('invoices')
    op.drop_table('global_time_slots')
    op.drop_table('drivers')
    with op.batch_alter_table('driver_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_positions_driver_id'))

    op.drop_table('driver_positions')
    op.drop_table('campaign_time_slots')
    op.drop_table('bookings')
    # ### end Alembic commands ###
